services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ${MCP_PATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${MCP_PATH}/frontend/home/build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
