services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../../MCP_119/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../MCP_119/frontend/home/build:/usr/share/nginx/html:ro
    ports:
      - "3037:80"
 