services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - D:\Project\codexProject\MCP_119\nginx\default.conf:/etc/nginx/conf.d/default.conf:ro
      - D:\Project\codexProject\MCP_119\frontend\home\build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
