services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: postgis
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: user
      DB_PASSWORD: 123456
      OLLAMA_URL: http://mds.com.tw:11434/api/generate
      ENABLE_LLM_SQL: "true"
    networks:
      - mcp911-network
    ports:
      - "8000:8000"

networks:
  mcp911-network:
    name: mcp911-network
    external: true
    driver: bridge