  services:
    postgis:
      image: postgis/postgis:15-3.4
      container_name: postgis
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: mydb
      networks:
        - mcp911-network
      volumes:
        - D:/Project/volumes/postgis_data:/var/lib/postgis/data
      ports:
        - "5432:5432"

    pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: yxchen0323@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 123456
      volumes:
        - D:/Project/volumes/pgadmin_data:/var/lib/pgadmin
      networks:
        - mcp911-network
      ports:
        - "5050:80"
      depends_on:
        - postgis

    backend:
      build:
        context: ./backend
      container_name: backend
      environment:
        DB_HOST: postgis
        DB_PORT: 5432
        DB_NAME: postgres
        DB_USER: user
        DB_PASSWORD: 123456
        OLLAMA_URL: http://host.docker.internal:11434/api/generate
        ENABLE_LLM_SQL: "true"
      networks:
        - mcp911-network
      ports:
        - "8000:8000"
      depends_on:
        - postgis

    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./frontend/home/build:/usr/share/nginx/html:ro
      networks:
        - mcp911-network
      ports:
        - "80:80"
      depends_on:
        - backend

  volumes:
    pgadmin_data:
    postgis_data:

  networks:
    mcp911-network:
      name: mcp911-network
      external: true
      driver: bridge