version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"

  fastapi:
    build:
      context: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/home/build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  postgres_data:
