services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: yxchen0323@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - ./valumes/pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./valumes/ollama_data:/root/.ollama

  fastapi:
    build:
      context: ./backend
    container_name: fastapi
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: 123456
      OLLAMA_URL: http://ollama:11434/api/generate
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ollama

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/home/build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  postgres_data:
  ollama_data:
  pgadmin_data:
