version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - D:/Project/volumes/postgis_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama-data: