services:
  postgis:
    image: postgis/postgis:15-3.4
    container_name: postgis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgis_data:/var/lib/postgis/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: yxchen0323@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - ./volumes/pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgis

volumes:
  pgadmin_data:
  postgis_data: